# Generated by Django 6.0.7 on 2026-08-03 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.CharField(blank=True, max_length=60)),
                ('question_type', models.CharField(default='sentence_choice', max_length=40)),
                ('prompt', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['vocabulary_set', 'source_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VocabularySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('level', models.PositiveIntegerField()),
                ('unit', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level', 'unit', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=120)),
                ('normalized_text', models.CharField(editable=False, max_length=120, unique=True)),
            ],
            options={
                'ordering': ['normalized_text'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='vocabulary.question')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_count', models.PositiveIntegerField()),
                ('points_per_question', models.PositiveIntegerField(default=5)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
                ('vocabulary_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='vocabulary.vocabularyset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='vocabulary.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_questions', to='vocabulary.question')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz_answers', to='vocabulary.questionchoice')),
                ('attempt_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='vocabulary.quizattemptquestion')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='vocabulary_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='vocabulary.vocabularyset'),
        ),
        migrations.CreateModel(
            name='WordSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_of_speech', models.CharField(choices=[('verb', 'verb'), ('noun', 'noun'), ('adjective', 'adjective'), ('adverb', 'adverb'), ('preposition', 'preposition'), ('other', 'other')], max_length=20)),
                ('meaning_zh', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='vocabulary.word')),
            ],
            options={
                'ordering': ['word__normalized_text', 'part_of_speech', 'meaning_zh'],
            },
        ),
        migrations.CreateModel(
            name='VocabularySetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('vocabulary_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vocabulary.vocabularyset')),
                ('word_sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_items', to='vocabulary.wordsense')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='word_sense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='vocabulary.wordsense'),
        ),
        migrations.AddConstraint(
            model_name='questionchoice',
            constraint=models.UniqueConstraint(fields=('question', 'label'), name='unique_question_choice_label'),
        ),
        migrations.AddConstraint(
            model_name='questionchoice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_question_choice_order'),
        ),
        migrations.AddConstraint(
            model_name='quizattemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question'),
        ),
        migrations.AddConstraint(
            model_name='quizattemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'display_order'), name='unique_attempt_display_order'),
        ),
        migrations.AddConstraint(
            model_name='wordsense',
            constraint=models.UniqueConstraint(fields=('word', 'part_of_speech', 'meaning_zh'), name='unique_word_sense'),
        ),
        migrations.AddConstraint(
            model_name='vocabularysetitem',
            constraint=models.UniqueConstraint(fields=('vocabulary_set', 'word_sense'), name='unique_vocabulary_set_item'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('vocabulary_set', 'source_id'), name='unique_question_source'),
        ),
    ]
