# Generated by Django 6.1 on 2026-08-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_active_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='selected_option_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='selected_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='direction',
            field=models.CharField(blank=True, choices=[('zh_to_en', '中文 → 英文'), ('en_to_zh', '英文 → 中文'), ('mixed', '雙向混合')], max_length=20),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_type',
            field=models.CharField(choices=[('sentence', '英文例句'), ('translation', '單字翻譯')], default='sentence', max_length=20),
        ),
        migrations.AddField(
            model_name='quizattemptquestion',
            name='correct_option_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattemptquestion',
            name='option_texts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quizattemptquestion',
            name='prompt_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizattemptquestion',
            name='question_direction',
            field=models.CharField(blank=True, choices=[('zh_to_en', '中文 → 英文'), ('en_to_zh', '英文 → 中文'), ('mixed', '雙向混合')], max_length=20),
        ),
    ]
